name: catalogo_web
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+13

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1
  equatable: ^2.0.5
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  firebase_storage: ^11.0.7
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  faker: ^2.0.0
  mocktail: ^0.3.0
  fake_cloud_firestore: ^2.0.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_app_name:
  name: "Parts Farm Paraguay"

flutter_icons:
  android: "ic_launcher"
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#4580C6"
  image_path: "assets/icon.png"
  remove_alpha_ios: true